<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="0" hostname="DESKTOP-1ICBAAR" failures="1" tests="1" name="regressionDose" time="5.022" errors="0" timestamp="2024-11-28T16:06:23 IST">
  <testcase classname="tests.LogOutTest" name="testInvalidUsername" time="5.016">
    <failure type="java.lang.AssertionError" message="Test failed due to exception.">
      <![CDATA[java.lang.AssertionError: Test failed due to exception.
at tests.LogOutTest.testInvalidUsername(LogOutTest.java:63)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1597)
... Removed 26 stack frames]]>
    </failure>
  </testcase> <!-- testInvalidUsername -->
</testsuite> <!-- regressionDose -->
